### PR TITLE
Update to 3.20.3

### PR DESCRIPTION
**Pull request by sh-shahrokhi**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Review by xylar — APPROVED** [review]
Looks good to me.  Needed for https://github.com/conda-forge/protobuf-feedstock/pull/183

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
Fine by me...

**Comment by xylar** [comment]
I'll rename the `3.20.1` branch to `3.20.x` after this for better clarity.

**Pull request merged**
