### PR TITLE
Backport fix for Tensorflow to 4.25.1

### PR DESCRIPTION
**Pull request by hmaarrfk**
Lets just see if this compiles

Closes https://github.com/conda-forge/libprotobuf-feedstock/issues/206

I mostly want to make it easy to take the action if it is deemed ok.

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Review by h-vetinari — APPROVED** [review]
LGTM! (I had forgotten that #202 hadn't been merged yet; I'll rebase it afterwards)

**Comment by h-vetinari** [comment]
The one failed test is a bit flaky...
```
[  FAILED  ] 1 test, listed below:
[  FAILED  ] MapImplTest.RandomOrdering
```

I'll try a restart once CI finishes

**Comment by hmaarrfk** [comment]
Thank you!

**Comment by traversaro** [comment]
> The one failed test is a bit flaky...
> 
> ```
> [  FAILED  ] 1 test, listed below:
> [  FAILED  ] MapImplTest.RandomOrdering
> ```
> 
> I'll try a restart once CI finishes

@h-vetinari The same test failed post merge: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=869556&view=logs&jobId=a70f640f-cc53-5cd3-6cdc-236a1aa90802&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802&t=6119ccbe-9301-594f-7c27-f792b80a7fcc . Can you please restart it? Thanks!

**Comment by xylar** [comment]
I just restarted CI.  Fingers crossed...

**Pull request merged**
