### PR TITLE
V3.5

### PR DESCRIPTION
**Pull request by hmaarrfk**
To sync OpenCV recipes with AnacondaDefaults, we need to rebuild libprotobuf 3.5.1(.1???) with the new compilers

https://github.com/conda-forge/opencv-feedstock/pull/146

cc: @mingwandroid 

I hope this is easy, otherwise I'll just use opencv vendored libprotobuf.

Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mingwandroid** [comment]
@jjhelmus looks after protobuffers. What is your advice Jonathan?

**Comment by xhochy** [comment]
@hmaarrfk FYI: I already tried and failed: https://github.com/conda-forge/libprotobuf-feedstock/pull/16

**Comment by hmaarrfk** [comment]
thanks  xhochy, I probably won't be wasting my time here then. 

I'll just vendor protobuf for linux and macosx.

**Comment by jakirkham** [comment]
Is this still needed @hmaarrfk?

**Comment by hmaarrfk** [comment]
no. thanks for the ping.

**Pull request closed without merging**
