### PR TITLE
libprotobuf v4.23.0

### PR DESCRIPTION
**Pull request by h-vetinari**
~Based on #155, will be rebased once that's in.~

Closes #157

### CODE REVIEW

**Comment by h-vetinari** [comment]
So this fails with:
```
src/google/protobuf/unittest.pb.cc:3084:73: error: temporary of non-literal type 'absl::lts_20230125::Cord' in a constant expression
 3084 |       TestCord::Impl_::_default_optional_bytes_cord_default_func_{})}} {}
```

Though we're using abseil 20230125.2 and not [20230125.3](https://github.com/protocolbuffers/protobuf/blob/v23.0/protobuf_deps.bzl#L45) like protobuf, the difference is [only](https://github.com/abseil/abseil-cpp/commits/lts_2023_01_25) one commit, and we've backported that one.

So while we've got abseil in the error log, I doubt that it has something to do with the unvendoring.

**Comment by h-vetinari** [comment]
Very unusually, linux-64 builds are the only ones that are failing, while everything else passes. So it must be related to the test targets (which we're not building on linux-aarch&ppc), and it's specific to GCC (i.e. doesn't appear with Clang & MSVC).

Any insights you might have on this would be much appreciated @coryan! :)

**Comment by coryan** [comment]
> Very unusually, linux-64 builds are the only ones that are [failing](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=704766&view=results), while everything else passes. So it must be related to the test targets (which we're not building on linux-aarch&ppc), and it's specific to GCC (i.e. doesn't appear with Clang & MSVC).

I think you are running into the problems fixed by https://github.com/protocolbuffers/protobuf/commit/ae7ec4ef97e09089eca99b3ffda300f166f6c161.  It only affects GCC because only GCC defaults to C++17 at the moment (that is a guess).

That patch will be part of 23.1:

https://github.com/protocolbuffers/protobuf/compare/v23.0...23.x

**Comment by h-vetinari** [comment]
> I think you are running into the problems fixed by https://github.com/protocolbuffers/protobuf/commit/ae7ec4ef97e09089eca99b3ffda300f166f6c161.

That looks bang on, thanks a lot!

> It only affects GCC because only GCC defaults to C++17 at the moment (that is a guess).

I switched to C++17 globally in #144 already, but as the commit message mentions it seems a GCC issue

**Pull request merged**
