### PR TITLE
MNT: rerender

### LINKED ISSUE #31: @conda-forge-admin please rerender
@conda-forge-admin please rerender

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #31.

Here's a checklist to do before merging.
- [ ] Bump the build number if needed.

Fixes #31

### CODE REVIEW

**Comment by jakirkham** [comment]
I tried restarting the build on `master` in case that helps.

ref: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=47855

**Comment by xhochy** [comment]
@jakirkham We need a new conda-build release. The only functioning version I saw was `3.18.2` but this was also moved to broken. Neither newer nor older versions work.

**Comment by jakirkham** [comment]
We have a few options.

1. Hack something into the CI scripts to install a newer conda-build
2. Copy the [`run_conda_forge_build_setup_*`]( https://github.com/conda-forge/conda-forge-ci-setup-feedstock/tree/master/recipe ) into our recipe, tweak, and re-render
3. Wait for a new conda-build release

Thoughts?

**Comment by xhochy** [comment]
I would fancy 3 but I have the feeling that nobody is working on that for the moment. The other two would work here but we would have to use them in any `aarch64` suppporting recipe which would make this a global hack.

**Pull request merged**
