### PR TITLE
libprotobuf 22.3 

### PR DESCRIPTION
**Pull request by sh-shahrokhi**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@sh-shahrokhi, I think we're going to need a little while before we can move to 22.x, see his comment:
https://github.com/conda-forge/protobuf-feedstock/pull/180#issuecomment-1449291208

@h-vetinari, any update on that?

**Comment by h-vetinari** [comment]
Waiting for [grpc 1.54](https://github.com/conda-forge/grpc-cpp-feedstock/pull/285) and the corresponding migration, which is [compatible](https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/4075#issuecomment-1422741357) with the new protobuf.

**Comment by xylar** [comment]
@h-vetinari, great thanks!

**Comment by sh-shahrokhi** [comment]
> @h-vetinari, great thanks!

ok so I close this for now

**Pull request closed without merging**
