### PR TITLE
3.12.2

### PR DESCRIPTION
**Pull request by xhochy**
cc @bollwyvl

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by bollwyvl** [comment]
This would be great! Good luck!

**Comment by bollwyvl** [comment]
Here's the fail:
```

[80/403] Building CXX object CMakeFiles\libprotoc.dir\D_\bld\libprotobuf_1594967687456\work\src\google\protobuf\compiler\code_generator.cc.obj
FAILED: CMakeFiles/libprotoc.dir/D_/bld/libprotobuf_1594967687456/work/src/google/protobuf/compiler/code_generator.cc.obj 
C:\PROGRA~2\MICROS~1\2017\ENTERP~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe  /nologo /TP -DGOOGLE_PROTOBUF_CMAKE_BUILD -DHAVE_ZLIB -DLIBPROTOC_EXPORTS -DPROTOBUF_USE_DLLS -Dlibprotoc_EXPORTS -I. -I%SRC_DIR%\src -I%SRC_DIR%\third_party\googletest\googlemock -I%SRC_DIR%\third_party\googletest\googletest -I%SRC_DIR%\third_party\googletest\googletest\include -I%SRC_DIR%\third_party\googletest\googlemock\include -I%PREFIX%\Library\include /DWIN32 /D_WINDOWS /W3 /GR /EHsc /MD /O2 /Ob2 /DNDEBUG   /MP /wd4018 /wd4065 /wd4146 /wd4244 /wd4251 /wd4267 /wd4305 /wd4307 /wd4309 /wd4334 /wd4355 /wd4506 /wd4800 /wd4996 /bigobj /showIncludes /FoCMakeFiles\libprotoc.dir\D_\bld\libprotobuf_1594967687456\work\src\google\protobuf\compiler\code_generator.cc.obj /FdCMakeFiles\libprotoc.dir\ /FS -c %SRC_DIR%\src\google\protobuf\compiler\code_generator.cc
%SRC_DIR%\src\google/protobuf/parse_context.h(760): error C2491: 'google::protobuf::internal::PackedEnumParser': definition of dllimport function not allowed
%SRC_DIR%\src\google/protobuf/parse_context.h(777): error C2491: 'google::protobuf::internal::PackedEnumParserArg': definition of dllimport function not allowed
[81/403] Linking CXX shared library libprotobuf-lite.dll
   Creating library libprotobuf-lite.lib and object libprotobuf-lite.exp
[82/403] Building CXX object CMakeFiles\libprotoc.dir\D_\bld\libprotobuf_1594967687456\work\src\google\protobuf\compiler\command_line_interface.cc.obj
FAILED: CMakeFiles/libprotoc.dir/D_/bld/libprotobuf_1594967687456/work/src/google/protobuf/compiler/command_line_interface.cc.obj 
C:\PROGRA~2\MICROS~1\2017\ENTERP~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe  /nologo /TP -DGOOGLE_PROTOBUF_CMAKE_BUILD -DHAVE_ZLIB -DLIBPROTOC_EXPORTS -DPROTOBUF_USE_DLLS -Dlibprotoc_EXPORTS -I. -I%SRC_DIR%\src -I%SRC_DIR%\third_party\googletest\googlemock -I%SRC_DIR%\third_party\googletest\googletest -I%SRC_DIR%\third_party\googletest\googletest\include -I%SRC_DIR%\third_party\googletest\googlemock\include -I%PREFIX%\Library\include /DWIN32 /D_WINDOWS /W3 /GR /EHsc /MD /O2 /Ob2 /DNDEBUG   /MP /wd4018 /wd4065 /wd4146 /wd4244 /wd4251 /wd4267 /wd4305 /wd4307 /wd4309 /wd4334 /wd4355 /wd4506 /wd4800 /wd4996 /bigobj /showIncludes /FoCMakeFiles\libprotoc.dir\D_\bld\libprotobuf_1594967687456\work\src\google\protobuf\compiler\command_line_interface.cc.obj /FdCMakeFiles\libprotoc.dir\ /FS -c %SRC_DIR%\src\google\protobuf\compiler\command_line_interface.cc
%SRC_DIR%\src\google/protobuf/parse_context.h(760): error C2491: 'google::protobuf::internal::PackedEnumParser': definition of dllimport function not allowed
%SRC_DIR%\src\google/protobuf/parse_context.h(777): error C2491: 'google::protobuf::internal::PackedEnumParserArg': definition of dllimport function not allowed
ninja: build stopped: subcommand failed.
```

Perhaps there's something in #57 we need to bring across?

**Comment by jakirkham** [comment]
Looks like `3.12.4` went in with PR ( https://github.com/conda-forge/libprotobuf-feedstock/pull/63 ). Do we still need `3.12.2` or should this be closed?

**Comment by bollwyvl** [comment]
I've been promised a dagster that resolves this in the future some time,
but if it's not a huge lift, it would be really nice to have this... But
not nice enough for me to fight with it 😉 Your time is very valuable as
well, of course!

**Comment by bollwyvl** [comment]
The promised `dagster 0.9.0` (which pins `protobuf==3.12.4`, which we have :tada: ) was released, so this can be closed from my perspective!

**Pull request closed without merging**
