### PR TITLE
libprotobuf 28.2

### PR DESCRIPTION
**Pull request by xhochy**
Fixes #230 

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Review by h-vetinari — APPROVED** [review]
v29.0 is already on rc1 - we could consider making that the next migration after 27.5; though I'd also be alright to migrate 28.x once things calm down a bit in the current migration.

**Comment by h-vetinari** [comment]
Thanks for cleaning up the patches by the way!

**Comment by xhochy** [comment]
Let's see first whether we get the Python package and `grpc` to build with this version :D

**Comment by h-vetinari** [comment]
Sure. Grpc also recently released a new version (1.67), so we could do two birds with one stone.

**Comment by xhochy** [comment]
> Sure. Grpc also recently released a new version (1.67), so we could do two birds with one stone.

I'm on that already locally. Sadly(?) `grpcio-tools` has only published `rc1` yet.

**Comment by h-vetinari** [comment]
> I'm on that already locally. Sadly(?) `grpcio-tools` has only published `rc1` yet.

We could build `grpcio-tools` from source -- it's the same repo anyway; when I did https://github.com/conda-forge/grpc-cpp-feedstock/pull/370 I just wanted to transpose the tools-feedstock and unblock grpc, not dive down yet another rabbit hole. But if it ends up not too hard, we'd spare ourselves the dependency on waiting for pypi releases.

**Pull request merged**
